---
- name: Install stuff, configure sites & DB's
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - common/timezone
    - common/base-packages
    - common/hostname
    - php/xdebug
    - php/php
    - mariadb/server
    - mariadb/client
    - nginx
    - nodejs
    - tools
