---
- stat: path=/home/vagrant/.nvm
  register: nvm

- name: Node | Install NVM
  when: nvm.stat.exists == False
  become: true
  become_user: vagrant
  shell: curl -o- {{nvm_download_url}} | bash

- name: Node | Install 8.9
  become: true
  become_user: vagrant
  shell: source /home/vagrant/.zshrc && nvm install 8.9 && nvm alias default 8.9
  args:
    executable: /bin/zsh

- name: Node | Install Yarn
  become: true
  become_user: vagrant
  shell: source /home/vagrant/.zshrc && npm i -g yarn
  args:
    executable: /bin/zsh
