- name: Check if web root exists
  stat: path={{ nginx_web_root }}
  register: web_root_stat

- name: Create web root directory
  file: path={{ nginx_web_root }} state=directory
  when: not web_root_stat.stat.exists

- name: Ensure web root directory has proper permissions
  file: path={{ nginx_web_root }}
        owner={{ nginx_user }}
        group={{ nginx_group }}
        mode="u=rwX,g=rwXs,o=rX"
  when: not web_root_stat.stat.exists
  
- name: Change default nginx site
  template: src={{ nginx_host_template }} dest={{ nginx_host_file }}
  notify: restart nginx
  
- name: Ensure the default site is enabled
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
