---
ip_addr: '192.168.69.99'
hostname: 'DevBox'
domains:
  -
    name: 'testsite.dev'
    db_name: 'testsite_dev'
    docroot: '/sites/testsite'
  -
    name: 'viaplay-customer-service.dev'
    db_name: 'viaplay-customer-service_dev'
    docroot: '/sites/viaplay-customer-service'
  -
    name: 'affecto.dev'
    db_name: 'affecto_dev'
    docroot: '/sites/affecto'
  -
    name: 'delingua.dev'
    db_name: 'delingua_dev'
    docroot: '/sites/delingua'
  -
    name: 'gamerefinery.dev'
    db_name: 'gamerefinery_dev'
    docroot: '/sites/gamerefinery'
  -
    name: 'kodit-io.dev'
    db_name: 'kodit-io_dev'
    docroot: '/sites/kodit-io'
  -
    name: 'visitrovaniemi.dev'
    db_name: 'visitrovaniemi_dev'
    docroot: '/sites/visitrovaniemi'
  -
    name: 'growthminds.dev'
    db_name: 'growthminds_dev'
    docroot: '/sites/growthminds'
  -
    name: 'jly.dev'
    db_name: 'jly_dev'
    docroot: '/sites/jly'
  -
    name: 'hel-pops.dev'
    db_name: 'hel-pops_dev'
    docroot: '/sites/hel-pops'
  -
    name: 'nattours.dev'
    db_name: 'nattours_dev'
    docroot: '/sites/nattours/web'
  -
    name: 'vaccindirekt.dev'
    db_name: 'vaccindirekt_dev'
    docroot: '/sites/vaccindirekt/web'
  -
    name: 'vaarallinenjate.dev'
    db_name: 'vaarallinenjate_dev'
    docroot: '/sites/vaarallinenjate/web'
  -
    name: 'dmcn.dev'
    db_name: 'dmcn_dev'
    docroot: '/sites/dmcn/web'
  -
    name: 'vaarallinenjate.dev'
    db_name: 'vaarallinenjate_dev'
    docroot: '/sites/vaarallinenjate/web'
  -
    name: 'opev.dev'
    db_name: 'opev_dev'
    docroot: '/sites/opev'
