#
# Installation
#
- name: Install packages
  apt: pkg={{ item }} state=present
  with_items: "{{ mariadb_packages }}"

#
# Configuration
#
- name: Configure my.cnf using template
  template: dest="/etc/mysql/my.cnf"
            src="my.cnf.j2"
  notify: restart mariadb

- name: Ensure service is started and enabled
  service: name=mysql state=started enabled=yes

- name: Get list of hosts for the root user
  command: mysql -u root -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mariadb_root_hosts
  changed_when: false

- name: Get list of hosts for the anonymous user
  command: mysql -u root -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mariadb_anonymous_hosts
  changed_when: false

- name: Remove anonymous users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mariadb_anonymous_hosts.stdout_lines }}"

- include_vars: ../../../../config.yml

- name: Remove test database
  mysql_db: "name='test' state=absent"

- name: Update database root password
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
  with_items: "{{ mariadb_root_hosts.stdout_lines }}"

- name: Copy .my.cnf file with root password credentials
  template:
    src: "user-my.cnf.j2"
    dest: "{{ mariadb_user_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Create databases
  mysql_db: name={{ item.db_name }} state=present login_user=root login_password={{ mariadb_root_password }}
  with_items: "{{ domains }}"

- name: Create users
  mysql_user: name={{ item.user }} password={{ item.password }} host={{ item.host }} priv={{ item.database }}.*:ALL state=present login_user=root login_password={{ mariadb_root_password }} append_privs=yes
  with_items: "{{ mariadb_users }}"
